<?php

namespace Database\Seeders;

use App\Models\PostalCode;
use App\Models\ShippingZone;
use Illuminate\Database\Seeder;

class PostalCodeSeeder extends Seeder
{
    public function run(): void
    {
        $codes = [
            // KACHIN STATE
            ['zone' => 'Kachin State', 'city' => 'Myitkyina', 'postal_code' => '01011'],
            ['zone' => 'Kachin State', 'city' => 'Phakant', 'postal_code' => '01161'],
            ['zone' => 'Kachin State', 'city' => 'Bhamaw', 'postal_code' => '01131'],
            ['zone' => 'Kachin State', 'city' => 'Putao', 'postal_code' => '01051'],
            ['zone' => 'Kachin State', 'city' => 'Mohnyin', 'postal_code' => '01111'],
            ['zone' => 'Kachin State', 'city' => 'Hopin', 'postal_code' => '01112'],
            ['zone' => 'Kachin State', 'city' => 'Myitkyina University', 'postal_code' => '01012'],
            ['zone' => 'Kachin State', 'city' => 'Namtee', 'postal_code' => '01101'],
            ['zone' => 'Kachin State', 'city' => 'Sarhmaw', 'postal_code' => '01102'],
            ['zone' => 'Kachin State', 'city' => 'Nanmar', 'postal_code' => '01113'],
            ['zone' => 'Kachin State', 'city' => 'Mapakha', 'postal_code' => '01015'],
            ['zone' => 'Kachin State', 'city' => 'Mogaung', 'postal_code' => '01103'],
            ['zone' => 'Kachin State', 'city' => 'Karmine', 'postal_code' => '01162'],
            ['zone' => 'Kachin State', 'city' => 'Chibwe', 'postal_code' => '01071'],
            ['zone' => 'Kachin State', 'city' => 'Shwegu', 'postal_code' => '01121'],
            ['zone' => 'Kachin State', 'city' => 'Momauk', 'postal_code' => '01151'],
            ['zone' => 'Kachin State', 'city' => 'Sunpayabom', 'postal_code' => '01061'],
            ['zone' => 'Kachin State', 'city' => 'Machanbaw', 'postal_code' => '01041'],
            ['zone' => 'Kachin State', 'city' => 'Khaunglanphu', 'postal_code' => '01181'],
            ['zone' => 'Kachin State', 'city' => 'Naungmon', 'postal_code' => '01031'],
            ['zone' => 'Kachin State', 'city' => 'Taning', 'postal_code' => '01091'],
            ['zone' => 'Kachin State', 'city' => 'Mansi', 'postal_code' => '01141'],
            ['zone' => 'Kachin State', 'city' => 'Waingmaw', 'postal_code' => '01081'],
            ['zone' => 'Kachin State', 'city' => 'Pinbaw', 'postal_code' => '01104'],
            ['zone' => 'Kachin State', 'city' => 'Nantmon', 'postal_code' => '01114'],
            ['zone' => 'Kachin State', 'city' => 'Mawhan', 'postal_code' => '01116'],
            ['zone' => 'Kachin State', 'city' => 'Bhamaw University', 'postal_code' => '01132'],
            ['zone' => 'Kachin State', 'city' => 'Sinbo', 'postal_code' => '01191'],
            ['zone' => 'Kachin State', 'city' => 'Tarlawgyi', 'postal_code' => '01016'],
            ['zone' => 'Kachin State', 'city' => 'Sadone', 'postal_code' => '01082'],
            ['zone' => 'Kachin State', 'city' => 'Kanbaiti', 'postal_code' => '01083'],
            ['zone' => 'Kachin State', 'city' => 'Manweingyi', 'postal_code' => '01142'],
            ['zone' => 'Kachin State', 'city' => 'Shinbweyan', 'postal_code' => '01092'],
            ['zone' => 'Kachin State', 'city' => 'Myohla', 'postal_code' => '01122'],
            ['zone' => 'Kachin State', 'city' => 'Nantsiaung', 'postal_code' => '01115'],
            ['zone' => 'Kachin State', 'city' => 'Shaduzut', 'postal_code' => '01163'],
            ['zone' => 'Kachin State', 'city' => 'Panwar', 'postal_code' => '01072'],
            ['zone' => 'Kachin State', 'city' => 'Sawlaw', 'postal_code' => '01171'],
            ['zone' => 'Kachin State', 'city' => 'Sinkham', 'postal_code' => '01123'],
            ['zone' => 'Kachin State', 'city' => 'Myothit', 'postal_code' => '01152'],
            ['zone' => 'Kachin State', 'city' => 'Dawphoneyan', 'postal_code' => '01153'],
            ['zone' => 'Kachin State', 'city' => 'Lwegel', 'postal_code' => '01154'],
            ['zone' => 'Kachin State', 'city' => 'Pannandin', 'postal_code' => '01032'],
            ['zone' => 'Kachin State', 'city' => 'Myothitgyi', 'postal_code' => '01017'],
            ['zone' => 'Kachin State', 'city' => 'Ingyanyan', 'postal_code' => '01201'],
            ['zone' => 'Kachin State', 'city' => 'Lonekhin', 'postal_code' => '01164'],
            ['zone' => 'Kachin State', 'city' => 'Aungmyintha', 'postal_code' => '01014'],
            ['zone' => 'Kachin State', 'city' => 'Nammana', 'postal_code' => '01105'],
            ['zone' => 'Kachin State', 'city' => 'Mankein', 'postal_code' => '01013'],
            ['zone' => 'Kachin State', 'city' => 'Pyihtaung', 'postal_code' => '01018'],
            ['zone' => 'Kachin State', 'city' => 'Warshaung', 'postal_code' => '01084'],
            ['zone' => 'Kachin State', 'city' => 'Mayan', 'postal_code' => '01106'],
            ['zone' => 'Kachin State', 'city' => 'Loneton', 'postal_code' => '01117'],
            ['zone' => 'Kachin State', 'city' => 'Seinlonkabar', 'postal_code' => '01155'],
            ['zone' => 'Kachin State', 'city' => 'Putao airport', 'postal_code' => '01052'],
            ['zone' => 'Kachin State', 'city' => 'Dunban', 'postal_code' => '01165'],
            ['zone' => 'Kachin State', 'city' => 'Khatcho', 'postal_code' => '01085'],

            // SAGAING REGION (mapped from SAGAING DIVISION)
            ['zone' => 'Sagaing Region', 'city' => 'Monywa', 'postal_code' => '02301'],
            ['zone' => 'Sagaing Region', 'city' => 'Sagaing', 'postal_code' => '02371'],
            ['zone' => 'Sagaing Region', 'city' => 'Shwebo', 'postal_code' => '02261'],
            ['zone' => 'Sagaing Region', 'city' => 'Katha', 'postal_code' => '02151'],
            ['zone' => 'Sagaing Region', 'city' => 'Kalemyo', 'postal_code' => '02091'],
            ['zone' => 'Sagaing Region', 'city' => 'Mawlaik', 'postal_code' => '02081'],
            ['zone' => 'Sagaing Region', 'city' => 'Khantee', 'postal_code' => '02031'],
            ['zone' => 'Sagaing Region', 'city' => 'Homalin', 'postal_code' => '02051'],
            ['zone' => 'Sagaing Region', 'city' => 'Tamu', 'postal_code' => '02071'],
            ['zone' => 'Sagaing Region', 'city' => 'Kawlin', 'postal_code' => '02181'],
            ['zone' => 'Sagaing Region', 'city' => 'Myinmu', 'postal_code' => '02341'],
            ['zone' => 'Sagaing Region', 'city' => 'Myaung', 'postal_code' => '02381'],
            ['zone' => 'Sagaing Region', 'city' => 'Khin U', 'postal_code' => '02231'],
            ['zone' => 'Sagaing Region', 'city' => 'Wetlet', 'postal_code' => '02281'],
            ['zone' => 'Sagaing Region', 'city' => 'Kantbalu', 'postal_code' => '02211'],
            ['zone' => 'Sagaing Region', 'city' => 'Kyunhla', 'postal_code' => '02201'],
            ['zone' => 'Sagaing Region', 'city' => 'Depeyin', 'postal_code' => '02251'],
            ['zone' => 'Sagaing Region', 'city' => 'Taze', 'postal_code' => '02221'],
            ['zone' => 'Sagaing Region', 'city' => 'Budalin', 'postal_code' => '02271'],
            ['zone' => 'Sagaing Region', 'city' => 'Ahyadaw', 'postal_code' => '02291'],
            ['zone' => 'Sagaing Region', 'city' => 'Chaung U', 'postal_code' => '02331'],
            ['zone' => 'Sagaing Region', 'city' => 'Yinmabin', 'postal_code' => '02311'],
            ['zone' => 'Sagaing Region', 'city' => 'Wuntho', 'postal_code' => '02171'],
            ['zone' => 'Sagaing Region', 'city' => 'Salingyi', 'postal_code' => '02321'],
            ['zone' => 'Sagaing Region', 'city' => 'Pale', 'postal_code' => '02351'],
            ['zone' => 'Sagaing Region', 'city' => 'Tigyaing', 'postal_code' => '02191'],
            ['zone' => 'Sagaing Region', 'city' => 'Sagainghills', 'postal_code' => '02376'],
            ['zone' => 'Sagaing Region', 'city' => 'Ywathitgyi', 'postal_code' => '02374'],
            ['zone' => 'Sagaing Region', 'city' => 'Ywahtaung', 'postal_code' => '02375'],
            ['zone' => 'Sagaing Region', 'city' => 'Yeu', 'postal_code' => '02241'],
            ['zone' => 'Sagaing Region', 'city' => 'Namakha', 'postal_code' => '02305'],
            ['zone' => 'Sagaing Region', 'city' => 'Kani', 'postal_code' => '02121'],
            ['zone' => 'Sagaing Region', 'city' => 'Kyaesintaung', 'postal_code' => '02322'],
            ['zone' => 'Sagaing Region', 'city' => 'Indaw', 'postal_code' => '02141'],
            ['zone' => 'Sagaing Region', 'city' => 'Banmauk', 'postal_code' => '02131'],
            ['zone' => 'Sagaing Region', 'city' => 'Tahan', 'postal_code' => '02092'],
            ['zone' => 'Sagaing Region', 'city' => 'Kalewa', 'postal_code' => '02101'],
            ['zone' => 'Sagaing Region', 'city' => 'Phaungpyin', 'postal_code' => '02061'],
            ['zone' => 'Sagaing Region', 'city' => 'Minkin', 'postal_code' => '02111'],
            ['zone' => 'Sagaing Region', 'city' => 'Mintha', 'postal_code' => '02072'],
            ['zone' => 'Sagaing Region', 'city' => 'Htamanthi', 'postal_code' => '02052'],
            ['zone' => 'Sagaing Region', 'city' => 'Layshee', 'postal_code' => '02041'],
            ['zone' => 'Sagaing Region', 'city' => 'Laheir', 'postal_code' => '02021'],
            ['zone' => 'Sagaing Region', 'city' => 'Nanyun', 'postal_code' => '02011'],
            ['zone' => 'Sagaing Region', 'city' => 'Pinlebu', 'postal_code' => '02161'],
            ['zone' => 'Sagaing Region', 'city' => 'Sartaung', 'postal_code' => '02372'],
            ['zone' => 'Sagaing Region', 'city' => 'Nyaungpinwine', 'postal_code' => '02373'],
            ['zone' => 'Sagaing Region', 'city' => 'Kyaukmyaung', 'postal_code' => '02262'],
            ['zone' => 'Sagaing Region', 'city' => 'Seikkon', 'postal_code' => '02263'],
            ['zone' => 'Sagaing Region', 'city' => 'Shwebo Collage', 'postal_code' => '02264'],
            ['zone' => 'Sagaing Region', 'city' => 'Hlataw', 'postal_code' => '02282'],
            ['zone' => 'Sagaing Region', 'city' => 'Kabo', 'postal_code' => '02215'],
            ['zone' => 'Sagaing Region', 'city' => 'Chatthin', 'postal_code' => '02213'],
            ['zone' => 'Sagaing Region', 'city' => 'Htantabin', 'postal_code' => '02214'],
            ['zone' => 'Sagaing Region', 'city' => 'Ahlon', 'postal_code' => '02303'],
            ['zone' => 'Sagaing Region', 'city' => 'MonywaCollage', 'postal_code' => '02304'],
            ['zone' => 'Sagaing Region', 'city' => 'Monywa (GTC)', 'postal_code' => '02306'],
            ['zone' => 'Sagaing Region', 'city' => 'Monywa Bazaar', 'postal_code' => '02302'],
            ['zone' => 'Sagaing Region', 'city' => 'Moda', 'postal_code' => '02152'],
            ['zone' => 'Sagaing Region', 'city' => 'Inywa', 'postal_code' => '02153'],
            ['zone' => 'Sagaing Region', 'city' => 'Mawluu', 'postal_code' => '02142'],
            ['zone' => 'Sagaing Region', 'city' => 'Nabar', 'postal_code' => '02143'],
            ['zone' => 'Sagaing Region', 'city' => 'Nankhan', 'postal_code' => '02172'],
            ['zone' => 'Sagaing Region', 'city' => 'Natchaung', 'postal_code' => '02093'],
            ['zone' => 'Sagaing Region', 'city' => 'Masein', 'postal_code' => '02102'],
            ['zone' => 'Sagaing Region', 'city' => 'Kindat', 'postal_code' => '02082'],
            ['zone' => 'Sagaing Region', 'city' => 'Minyar', 'postal_code' => '02063'],
            ['zone' => 'Sagaing Region', 'city' => 'Thanga', 'postal_code' => '02062'],
            ['zone' => 'Sagaing Region', 'city' => 'Uaungzayya', 'postal_code' => '02073'],
            ['zone' => 'Sagaing Region', 'city' => 'Bandoola', 'postal_code' => '02074'],
            ['zone' => 'Sagaing Region', 'city' => 'Myothit', 'postal_code' => '02075'],
            ['zone' => 'Sagaing Region', 'city' => 'Khanpart', 'postal_code' => '02076'],
            ['zone' => 'Sagaing Region', 'city' => 'Naungpoaung', 'postal_code' => '02053'],
            ['zone' => 'Sagaing Region', 'city' => 'Pansaug', 'postal_code' => '02012'],
            ['zone' => 'Sagaing Region', 'city' => 'Kyarpin', 'postal_code' => '02112'],
            ['zone' => 'Sagaing Region', 'city' => 'Meza', 'postal_code' => '02144'],
            ['zone' => 'Sagaing Region', 'city' => 'Mowinelute', 'postal_code' => '02142'],
            ['zone' => 'Sagaing Region', 'city' => 'Htanparkhwe', 'postal_code' => '02022'],
            ['zone' => 'Sagaing Region', 'city' => 'Donhee', 'postal_code' => '02013'],
            ['zone' => 'Sagaing Region', 'city' => 'Padu', 'postal_code' => '02377'],
            ['zone' => 'Sagaing Region', 'city' => 'Paline', 'postal_code' => '02265'],
            ['zone' => 'Sagaing Region', 'city' => 'HtanKone', 'postal_code' => '02216'],
            ['zone' => 'Sagaing Region', 'city' => 'Sonechaung', 'postal_code' => '02307'],
            ['zone' => 'Sagaing Region', 'city' => 'Nyaungpingyi', 'postal_code' => '02308'],
            ['zone' => 'Sagaing Region', 'city' => 'Khinmon', 'postal_code' => '02332'],
            ['zone' => 'Sagaing Region', 'city' => 'Kin', 'postal_code' => '02122'],
            ['zone' => 'Sagaing Region', 'city' => 'Mintaingpin', 'postal_code' => '02352'],
            ['zone' => 'Sagaing Region', 'city' => 'Koehtaungbo', 'postal_code' => '02182'],
            ['zone' => 'Sagaing Region', 'city' => 'Joehtaung', 'postal_code' => '02173'],
            ['zone' => 'Sagaing Region', 'city' => 'Myokesee', 'postal_code' => '02094'],
            ['zone' => 'Sagaing Region', 'city' => 'Taungthut', 'postal_code' => '02064'],
            ['zone' => 'Sagaing Region', 'city' => 'Moukkataw', 'postal_code' => '02113'],
            ['zone' => 'Sagaing Region', 'city' => 'Thazi', 'postal_code' => '02309'],

            // CHIN STATE
            ['zone' => 'Chin State', 'city' => 'Hakha', 'postal_code' => '03011'],
            ['zone' => 'Chin State', 'city' => 'Falam', 'postal_code' => '03031'],
            ['zone' => 'Chin State', 'city' => 'Mindat', 'postal_code' => '03071'],
            ['zone' => 'Chin State', 'city' => 'Teetain', 'postal_code' => '03041'],
            ['zone' => 'Chin State', 'city' => 'Matupi', 'postal_code' => '03061'],
            ['zone' => 'Chin State', 'city' => 'Kalay University', 'postal_code' => '03044'],
            ['zone' => 'Chin State', 'city' => 'Htantalan', 'postal_code' => '03021'],
            ['zone' => 'Chin State', 'city' => 'Htotehlaing', 'postal_code' => '03042'],
            ['zone' => 'Chin State', 'city' => 'Tunzan', 'postal_code' => '03051'],
            ['zone' => 'Chin State', 'city' => 'Kanpetlat', 'postal_code' => '03081'],
            ['zone' => 'Chin State', 'city' => 'Reed', 'postal_code' => '03033'],
            ['zone' => 'Chin State', 'city' => 'Rezwa', 'postal_code' => '03062'],
            ['zone' => 'Chin State', 'city' => 'Su-Khua', 'postal_code' => '03012'],
            ['zone' => 'Chin State', 'city' => 'Loneban', 'postal_code' => '03032'],
            ['zone' => 'Chin State', 'city' => 'Hnarain', 'postal_code' => '03022'],
            ['zone' => 'Chin State', 'city' => 'Kattel', 'postal_code' => '03043'],
            ['zone' => 'Chin State', 'city' => 'Kyeekhar', 'postal_code' => '03052'],
            ['zone' => 'Chin State', 'city' => 'Dokeywar', 'postal_code' => '03072'],
            ['zone' => 'Chin State', 'city' => 'Lailanpi', 'postal_code' => '03063'],
            ['zone' => 'Chin State', 'city' => 'Sabaung the', 'postal_code' => '03065'],
            ['zone' => 'Chin State', 'city' => 'Zokwar', 'postal_code' => '03013'],
            ['zone' => 'Chin State', 'city' => 'Satter', 'postal_code' => '03014'],
            ['zone' => 'Chin State', 'city' => 'Ramkala', 'postal_code' => '03034'],
            ['zone' => 'Chin State', 'city' => 'Kalawmon', 'postal_code' => '03035'],
            ['zone' => 'Chin State', 'city' => 'Thikee', 'postal_code' => '03023'],
            ['zone' => 'Chin State', 'city' => 'Faroom', 'postal_code' => '03024'],
            ['zone' => 'Chin State', 'city' => 'Harainkhan', 'postal_code' => '03025'],
            ['zone' => 'Chin State', 'city' => 'Khonkyone', 'postal_code' => '03015'],
            ['zone' => 'Chin State', 'city' => 'Thinan', 'postal_code' => '03016'],
            ['zone' => 'Chin State', 'city' => 'Tweehtan', 'postal_code' => '03045'],
            ['zone' => 'Chin State', 'city' => 'Makweinnuu', 'postal_code' => '03073'],
            ['zone' => 'Chin State', 'city' => 'Oakka', 'postal_code' => '03064'],
            ['zone' => 'Chin State', 'city' => 'Mamata', 'postal_code' => '03074'],
            ['zone' => 'Chin State', 'city' => 'Aukchang', 'postal_code' => '03075'],
            ['zone' => 'Chin State', 'city' => 'Darochain', 'postal_code' => '03017'],
            ['zone' => 'Chin State', 'city' => 'Saizang', 'postal_code' => '03046'],
            ['zone' => 'Chin State', 'city' => 'Shinbaung', 'postal_code' => '03082'],

            // MAGWAY REGION (from MAGWAY DIVISION)
            ['zone' => 'Magway Region', 'city' => 'Aunglan', 'postal_code' => '04151'],
            ['zone' => 'Magway Region', 'city' => 'Kyawswa', 'postal_code' => '04152'],
            ['zone' => 'Magway Region', 'city' => 'Pyalo', 'postal_code' => '04153'],
            // Note: some postal codes missing, skip rows with '-'
            ['zone' => 'Magway Region', 'city' => 'Chauk', 'postal_code' => '04171'],
            ['zone' => 'Magway Region', 'city' => 'Salay', 'postal_code' => '04172'],
            ['zone' => 'Magway Region', 'city' => 'Chauk (GTC)', 'postal_code' => '04174'],
            ['zone' => 'Magway Region', 'city' => 'Gwaycho', 'postal_code' => '04173'],
            ['zone' => 'Magway Region', 'city' => 'Gwaybin', 'postal_code' => '04175'],
            ['zone' => 'Magway Region', 'city' => 'Pakhanngwe', 'postal_code' => '04176'],
            ['zone' => 'Magway Region', 'city' => 'Gantgaw', 'postal_code' => '04211'],
            ['zone' => 'Magway Region', 'city' => 'Kyaw', 'postal_code' => '04212'],
            ['zone' => 'Magway Region', 'city' => 'Kanywa', 'postal_code' => '04214'],
            ['zone' => 'Magway Region', 'city' => 'Hanthawaddy', 'postal_code' => '04215'],
            ['zone' => 'Magway Region', 'city' => 'Minywa', 'postal_code' => '04216'],
            ['zone' => 'Magway Region', 'city' => 'Htilinn', 'postal_code' => '04221'],
            ['zone' => 'Magway Region', 'city' => 'Kyin', 'postal_code' => '04222'],
            ['zone' => 'Magway Region', 'city' => 'Kanma (Thayet)', 'postal_code' => '04111'],
            ['zone' => 'Magway Region', 'city' => 'Kyobin', 'postal_code' => '04112'],
            ['zone' => 'Magway Region', 'city' => 'Yenantha', 'postal_code' => '04113'],
            ['zone' => 'Magway Region', 'city' => 'Magwe', 'postal_code' => '04011'],
            ['zone' => 'Magway Region', 'city' => 'Michaungye', 'postal_code' => '04014'],
            ['zone' => 'Magway Region', 'city' => 'Magwe University', 'postal_code' => '04012'],
            ['zone' => 'Magway Region', 'city' => 'Yanpae (Magwe)', 'postal_code' => '04016'],
            ['zone' => 'Magway Region', 'city' => 'Myinkwon', 'postal_code' => '04013'],
            ['zone' => 'Magway Region', 'city' => 'Thityarkauk', 'postal_code' => '04015'],
            ['zone' => 'Magway Region', 'city' => 'Thityarkauk (M.C)', 'postal_code' => '04017'],
            ['zone' => 'Magway Region', 'city' => 'Basic Healt Unversity', 'postal_code' => '04018'],
            ['zone' => 'Magway Region', 'city' => 'Minbu', 'postal_code' => '04021'],
            ['zone' => 'Magway Region', 'city' => 'Sagu', 'postal_code' => '04023'],
            ['zone' => 'Magway Region', 'city' => 'Manyenanmyae', 'postal_code' => '04025'],
            ['zone' => 'Magway Region', 'city' => 'Minbuzay', 'postal_code' => '04022'],
            ['zone' => 'Magway Region', 'city' => 'Mindonn', 'postal_code' => '04101'],
            ['zone' => 'Magway Region', 'city' => 'Minhla (Thayet)', 'postal_code' => '04071'],
            ['zone' => 'Magway Region', 'city' => 'Malon', 'postal_code' => '04072'],
            ['zone' => 'Magway Region', 'city' => 'Kantoke', 'postal_code' => '04073'],
            ['zone' => 'Magway Region', 'city' => 'Myaing', 'postal_code' => '04191'],
            ['zone' => 'Magway Region', 'city' => 'Linkataw', 'postal_code' => '04192'],
            ['zone' => 'Magway Region', 'city' => 'Myothit', 'postal_code' => '04131'],
            ['zone' => 'Magway Region', 'city' => 'Myolulin', 'postal_code' => '04132'],
            ['zone' => 'Magway Region', 'city' => 'Natmauk', 'postal_code' => '04121'],
            ['zone' => 'Magway Region', 'city' => 'Innkan', 'postal_code' => '04122'],
            ['zone' => 'Magway Region', 'city' => 'Layeain', 'postal_code' => '04123'],
            ['zone' => 'Magway Region', 'city' => 'Shwepantaw', 'postal_code' => '04124'],
            ['zone' => 'Magway Region', 'city' => 'Ngaphe', 'postal_code' => '04061'],
            ['zone' => 'Magway Region', 'city' => 'Goatgyi', 'postal_code' => '04062'], // from Ngape
            ['zone' => 'Magway Region', 'city' => 'Sinchitaing', 'postal_code' => '04062?'], // duplicate? using 04062 for now
            // Actually we need to be careful: the data may have multiple entries with same code. We'll include all distinct.
            ['zone' => 'Magway Region', 'city' => 'Pakokku', 'postal_code' => '04201'],
            ['zone' => 'Magway Region', 'city' => 'Myitchay', 'postal_code' => '04203'],
            ['zone' => 'Magway Region', 'city' => 'Kanma(PKU)', 'postal_code' => '04206'],
            ['zone' => 'Magway Region', 'city' => 'Warzi', 'postal_code' => '04203'],
            ['zone' => 'Magway Region', 'city' => 'Pakokku Myoma (Pakokku University)', 'postal_code' => '04202'],
            ['zone' => 'Magway Region', 'city' => 'Kyunchaung', 'postal_code' => '04204'],
            ['zone' => 'Magway Region', 'city' => 'Pauk', 'postal_code' => '04231'],
            ['zone' => 'Magway Region', 'city' => 'Yepyar', 'postal_code' => '04232'],
            ['zone' => 'Magway Region', 'city' => 'Pwintpyu', 'postal_code' => '04031'],
            ['zone' => 'Magway Region', 'city' => 'Konezoung', 'postal_code' => '04032'],
            ['zone' => 'Magway Region', 'city' => 'Shaukttaw', 'postal_code' => '04033'],
            ['zone' => 'Magway Region', 'city' => 'Kyaungtawya', 'postal_code' => '04034'],
            ['zone' => 'Magway Region', 'city' => 'Laekaing', 'postal_code' => '04036'],
            ['zone' => 'Magway Region', 'city' => 'Mezali', 'postal_code' => '04035'],
            ['zone' => 'Magway Region', 'city' => 'Sinphyukyun', 'postal_code' => '04042'],
            ['zone' => 'Magway Region', 'city' => 'Salinn', 'postal_code' => '04041'],
            ['zone' => 'Magway Region', 'city' => 'Tanyaung', 'postal_code' => '04044'],
            ['zone' => 'Magway Region', 'city' => 'Linzinn', 'postal_code' => '04043'],
            ['zone' => 'Magway Region', 'city' => 'Kanpyar', 'postal_code' => '04045'],
            ['zone' => 'Magway Region', 'city' => 'Saw', 'postal_code' => '04241'],
            ['zone' => 'Magway Region', 'city' => 'Kyaukhtu', 'postal_code' => '04242'],
            ['zone' => 'Magway Region', 'city' => 'Laungshe', 'postal_code' => '04243'],
            ['zone' => 'Magway Region', 'city' => 'Saytoketaya', 'postal_code' => '04051'],
            ['zone' => 'Magway Region', 'city' => 'Seikpyu', 'postal_code' => '04251'],
            ['zone' => 'Magway Region', 'city' => 'Chintaungy', 'postal_code' => '04252'],
            ['zone' => 'Magway Region', 'city' => 'Sinpaungwe', 'postal_code' => '04081'],
            ['zone' => 'Magway Region', 'city' => 'Koebin', 'postal_code' => '04082'],
            ['zone' => 'Magway Region', 'city' => 'Taungtwingyi', 'postal_code' => '04141'],
            ['zone' => 'Magway Region', 'city' => 'Chaungnet', 'postal_code' => '04144'],
            ['zone' => 'Magway Region', 'city' => 'Sattwar', 'postal_code' => '04142'],
            ['zone' => 'Magway Region', 'city' => 'Kokkogwa', 'postal_code' => '04143'],
            ['zone' => 'Magway Region', 'city' => 'Thayet', 'postal_code' => '04091'],
            ['zone' => 'Magway Region', 'city' => 'Thayet Zay', 'postal_code' => '04092'],
            ['zone' => 'Magway Region', 'city' => 'Yenanchaung', 'postal_code' => '04161'],
            ['zone' => 'Magway Region', 'city' => 'Nyaunghla', 'postal_code' => '04163'],
            ['zone' => 'Magway Region', 'city' => 'Lathmatkone', 'postal_code' => '04162'],
            ['zone' => 'Magway Region', 'city' => 'Pinwa', 'postal_code' => '04164'],
            ['zone' => 'Magway Region', 'city' => 'Yezakyo', 'postal_code' => '04181'],
            ['zone' => 'Magway Region', 'city' => 'Kyetsukyin', 'postal_code' => '04183'],
            ['zone' => 'Magway Region', 'city' => 'Pakhamgyi', 'postal_code' => '04184'],
            ['zone' => 'Magway Region', 'city' => 'Myaydaw', 'postal_code' => '04186'],
            ['zone' => 'Magway Region', 'city' => 'Maunge', 'postal_code' => '04182'],

            // MANDALAY REGION (mapped to 'Mandalay' zone)
            ['zone' => 'Mandalay', 'city' => 'Amarapura', 'postal_code' => '05061'],
            ['zone' => 'Mandalay', 'city' => 'Myitnge', 'postal_code' => '05062'],
            ['zone' => 'Mandalay', 'city' => 'Yadanarpon University', 'postal_code' => '05063'],
            ['zone' => 'Mandalay', 'city' => 'Boneoh', 'postal_code' => '05064'],
            ['zone' => 'Mandalay', 'city' => 'Mandalay (GPO)', 'postal_code' => '05011'],
            ['zone' => 'Mandalay', 'city' => 'Man (myaukpyin)', 'postal_code' => '05013'],
            ['zone' => 'Mandalay', 'city' => 'Mandalay Nantwin', 'postal_code' => '05012'],
            ['zone' => 'Mandalay', 'city' => 'Man (Ashaepyin)', 'postal_code' => '05014'],
            ['zone' => 'Mandalay', 'city' => 'Eaindawya', 'postal_code' => '05015'],
            ['zone' => 'Mandalay', 'city' => 'Yonegyi', 'postal_code' => '05021'],
            ['zone' => 'Mandalay', 'city' => 'Man(West)', 'postal_code' => '05022'],
            ['zone' => 'Mandalay', 'city' => 'Zaycho', 'postal_code' => '05023'],
            ['zone' => 'Mandalay', 'city' => 'Mandalay Railway Station', 'postal_code' => '05024'],
            ['zone' => 'Mandalay', 'city' => 'Chanmyathazi', 'postal_code' => '05041'],
            ['zone' => 'Mandalay', 'city' => 'Kyaukpadaung', 'postal_code' => '05241'],
            ['zone' => 'Mandalay', 'city' => 'Popa', 'postal_code' => '05242'],
            ['zone' => 'Mandalay', 'city' => 'Kyaukse', 'postal_code' => '05151'],
            ['zone' => 'Mandalay', 'city' => 'Thanywa', 'postal_code' => '05152'],
            ['zone' => 'Mandalay', 'city' => 'Bellin', 'postal_code' => '05143'],
            ['zone' => 'Mandalay', 'city' => 'Madaya', 'postal_code' => '05121'],
            ['zone' => 'Mandalay', 'city' => 'Shanzu', 'postal_code' => '05031'],
            ['zone' => 'Mandalay', 'city' => 'Mandalay (University)', 'postal_code' => '05032'],
            ['zone' => 'Mandalay', 'city' => 'Kungyan', 'postal_code' => '05033'],
            ['zone' => 'Mandalay', 'city' => 'Mahlaing', 'postal_code' => '05201'],
            ['zone' => 'Mandalay', 'city' => 'Meikhtila', 'postal_code' => '05181'],
            ['zone' => 'Mandalay', 'city' => 'Meikhtila Cantonment', 'postal_code' => '05182'],
            ['zone' => 'Mandalay', 'city' => 'Meikhtila(BaSaKa)', 'postal_code' => '05183'],
            ['zone' => 'Mandalay', 'city' => 'Shante', 'postal_code' => '05184'],
            ['zone' => 'Mandalay', 'city' => 'Shanmange', 'postal_code' => '05185'],
            ['zone' => 'Mandalay', 'city' => 'Kantaung', 'postal_code' => '05186'],
            ['zone' => 'Mandalay', 'city' => 'Mogoke', 'postal_code' => '05091'],
            ['zone' => 'Mandalay', 'city' => 'Kyatpyin', 'postal_code' => '05092'],
            ['zone' => 'Mandalay', 'city' => 'Myingyan', 'postal_code' => '05251'],
            ['zone' => 'Mandalay', 'city' => 'Myingyan Myoma', 'postal_code' => '05252'],
            ['zone' => 'Mandalay', 'city' => 'Semekhone', 'postal_code' => '05253'],
            ['zone' => 'Mandalay', 'city' => 'Myitthar', 'postal_code' => '05161'],
            ['zone' => 'Mandalay', 'city' => 'Kume', 'postal_code' => '05162'],
            ['zone' => 'Mandalay', 'city' => 'Nahtoegyi', 'postal_code' => '05261'],
            ['zone' => 'Mandalay', 'city' => 'Pyinsi', 'postal_code' => '05262'],
            ['zone' => 'Mandalay', 'city' => 'Ngazune', 'postal_code' => '05281'],
            ['zone' => 'Mandalay', 'city' => 'Myotha', 'postal_code' => '05282'],
            ['zone' => 'Mandalay', 'city' => 'NyaungOo', 'postal_code' => '05231'],
            ['zone' => 'Mandalay', 'city' => 'Bagan', 'postal_code' => '05232'],
            ['zone' => 'Mandalay', 'city' => 'Singu', 'postal_code' => '05233'],
            ['zone' => 'Mandalay', 'city' => 'Ngathayouk', 'postal_code' => '05234'],
            ['zone' => 'Mandalay', 'city' => 'Latpanchaypaw', 'postal_code' => '05236'],
            ['zone' => 'Mandalay', 'city' => 'Taungzinn', 'postal_code' => '05235'],
            ['zone' => 'Mandalay', 'city' => 'Nganhmargyi', 'postal_code' => '05283'],
            ['zone' => 'Mandalay', 'city' => 'Patheingyi', 'postal_code' => '05071'],
            ['zone' => 'Mandalay', 'city' => 'MTU', 'postal_code' => '05072'],
            ['zone' => 'Mandalay', 'city' => 'Htonbo', 'postal_code' => '05073'],
            ['zone' => 'Mandalay', 'city' => 'Pyawbwe', 'postal_code' => '05211'],
            ['zone' => 'Mandalay', 'city' => 'Yanaung', 'postal_code' => '05212'],
            ['zone' => 'Mandalay', 'city' => 'Pyaygyidakhon', 'postal_code' => '05051'],
            ['zone' => 'Mandalay', 'city' => 'Sathmutmyothit', 'postal_code' => '05052'],
            ['zone' => 'Mandalay', 'city' => 'PyinOoLwin', 'postal_code' => '05081'],
            ['zone' => 'Mandalay', 'city' => 'PyinOoLwinCantonment', 'postal_code' => '05082'],
            ['zone' => 'Mandalay', 'city' => 'CSTC', 'postal_code' => '05083'],
            ['zone' => 'Mandalay', 'city' => 'Padaythamyothit', 'postal_code' => '05084'],
            ['zone' => 'Mandalay', 'city' => 'Ahneesakhan', 'postal_code' => '05085'],
            ['zone' => 'Mandalay', 'city' => 'Wetwun', 'postal_code' => '05086'],
            ['zone' => 'Mandalay', 'city' => 'Latpanhla', 'postal_code' => '05112'],
            ['zone' => 'Mandalay', 'city' => 'Sintgu', 'postal_code' => '05111'],
            ['zone' => 'Mandalay', 'city' => 'Htonegyi', 'postal_code' => '05113'],
            ['zone' => 'Mandalay', 'city' => 'Sintkaing', 'postal_code' => '05141'],
            ['zone' => 'Mandalay', 'city' => 'Paleik', 'postal_code' => '05142'],
            ['zone' => 'Mandalay', 'city' => 'Tadau', 'postal_code' => '05131'],
            ['zone' => 'Mandalay', 'city' => 'Taungtha', 'postal_code' => '05271'],
            ['zone' => 'Mandalay', 'city' => 'Welaung', 'postal_code' => '05272'],
            ['zone' => 'Mandalay', 'city' => 'Yonesingyi', 'postal_code' => '05273'],
            ['zone' => 'Mandalay', 'city' => 'Ywathit', 'postal_code' => '05274'],
            ['zone' => 'Mandalay', 'city' => 'Semekan', 'postal_code' => '05275'],
            ['zone' => 'Mandalay', 'city' => 'Thabeikkyin', 'postal_code' => '05101'],
            ['zone' => 'Mandalay', 'city' => 'Dagaung', 'postal_code' => '05102'],
            ['zone' => 'Mandalay', 'city' => 'Tharzi', 'postal_code' => '05191'],
            ['zone' => 'Mandalay', 'city' => 'Hanza', 'postal_code' => '05192'],
            ['zone' => 'Mandalay', 'city' => 'Nyaungyan', 'postal_code' => '05193'],
            ['zone' => 'Mandalay', 'city' => 'Wundwin', 'postal_code' => '05171'],
            ['zone' => 'Mandalay', 'city' => 'Thedaw', 'postal_code' => '05172'],
            ['zone' => 'Mandalay', 'city' => 'Yamethin', 'postal_code' => '05221'],
            ['zone' => 'Mandalay', 'city' => 'Theinkonegyi', 'postal_code' => '05222'],

            // SHAN STATE
            ['zone' => 'Shan State', 'city' => 'Chinshwehaw', 'postal_code' => '06482'],
            ['zone' => 'Shan State', 'city' => 'Homain', 'postal_code' => '06202'],
            ['zone' => 'Shan State', 'city' => 'Hopan', 'postal_code' => '06391'],
            ['zone' => 'Shan State', 'city' => 'Hopan', 'postal_code' => '06392'], // Nanttit
            ['zone' => 'Shan State', 'city' => 'Hopan', 'postal_code' => '06393'], // Panlone
            ['zone' => 'Shan State', 'city' => 'Hopone', 'postal_code' => '06091'],
            ['zone' => 'Shan State', 'city' => 'Hopone', 'postal_code' => '06092'], // Kyaukkacha
            ['zone' => 'Shan State', 'city' => 'Hopone', 'postal_code' => '06093'], // Kyauktan
            ['zone' => 'Shan State', 'city' => 'Inndaw', 'postal_code' => '06073'],
            ['zone' => 'Shan State', 'city' => 'Kalaw', 'postal_code' => '06022'], // Aungpan
            ['zone' => 'Shan State', 'city' => 'Kalaw', 'postal_code' => '06024'], // Bawsai
            ['zone' => 'Shan State', 'city' => 'Kalaw', 'postal_code' => '06023'], // Heho
            ['zone' => 'Shan State', 'city' => 'Kalaw', 'postal_code' => '06021'],
            ['zone' => 'Shan State', 'city' => 'Kalaw', 'postal_code' => '06025'], // Wetpyuyae
            ['zone' => 'Shan State', 'city' => 'Karli', 'postal_code' => '06213'],
            ['zone' => 'Shan State', 'city' => 'Khollan', 'postal_code' => '06163'],
            ['zone' => 'Shan State', 'city' => 'Khonegyan', 'postal_code' => '06531'],
            ['zone' => 'Shan State', 'city' => 'Konhein', 'postal_code' => '06211'],
            ['zone' => 'Shan State', 'city' => 'Konhein', 'postal_code' => '06212'], // Tarkaw
            ['zone' => 'Shan State', 'city' => 'Konlon', 'postal_code' => '06381'],
            ['zone' => 'Shan State', 'city' => 'Kutkai', 'postal_code' => '06374'], // Kaungkhar
            ['zone' => 'Shan State', 'city' => 'Kutkai', 'postal_code' => '06372'],
            ['zone' => 'Shan State', 'city' => 'Kutkai', 'postal_code' => '06373'], // Nantphatka
            ['zone' => 'Shan State', 'city' => 'Kutkai', 'postal_code' => '06371'], // Tamoehnye
            ['zone' => 'Shan State', 'city' => 'Kyainglatt', 'postal_code' => '06273'],
            ['zone' => 'Shan State', 'city' => 'Kyainglatt', 'postal_code' => '06274'], // Wanpon
            ['zone' => 'Shan State', 'city' => 'Kyaingtaung', 'postal_code' => '06172'],
            ['zone' => 'Shan State', 'city' => 'Kyaingtong', 'postal_code' => '06231'],
            ['zone' => 'Shan State', 'city' => 'Kyaingtong', 'postal_code' => '06233'], // Loimwe
            ['zone' => 'Shan State', 'city' => 'Kyaingtong', 'postal_code' => '06234'], // Minekai
            ['zone' => 'Shan State', 'city' => 'Kyaukme', 'postal_code' => '06321'],
            ['zone' => 'Shan State', 'city' => 'Kyaukme', 'postal_code' => '06322'], // Maingngwet
            ['zone' => 'Shan State', 'city' => 'Kyaukme', 'postal_code' => '06325'], // Maingtin
            ['zone' => 'Shan State', 'city' => 'Kyaukme', 'postal_code' => '06323'], // Naungpain
            ['zone' => 'Shan State', 'city' => 'Kyauktalone', 'postal_code' => '06016'],
            ['zone' => 'Shan State', 'city' => 'Kyaythee', 'postal_code' => '06151'],
            ['zone' => 'Shan State', 'city' => 'Kyaythee', 'postal_code' => '06153'], // Wansin
            ['zone' => 'Shan State', 'city' => 'Laecha', 'postal_code' => '06121'],
            ['zone' => 'Shan State', 'city' => 'Lashio', 'postal_code' => '06301'],
            ['zone' => 'Shan State', 'city' => 'Lashio', 'postal_code' => '06302'], // Lashiogyi
            ['zone' => 'Shan State', 'city' => 'Lashio', 'postal_code' => '06304'], // Maingyaw
            ['zone' => 'Shan State', 'city' => 'Lashio', 'postal_code' => '06303'], // Mansanyaekya
            ['zone' => 'Shan State', 'city' => 'Laukkaing', 'postal_code' => '06481'],
            ['zone' => 'Shan State', 'city' => 'Linkhe', 'postal_code' => '06191'],
            ['zone' => 'Shan State', 'city' => 'Loilin', 'postal_code' => '06111'],
            ['zone' => 'Shan State', 'city' => 'Loilin', 'postal_code' => '06112'], // Minepon
            ['zone' => 'Shan State', 'city' => 'Mabain', 'postal_code' => '06451'],
            ['zone' => 'Shan State', 'city' => 'Manton', 'postal_code' => '06541'],
            ['zone' => 'Shan State', 'city' => 'Maukmai', 'postal_code' => '06182'], // Kaduugyi
            ['zone' => 'Shan State', 'city' => 'Maukmai', 'postal_code' => '06181'],
            ['zone' => 'Shan State', 'city' => 'Minekai', 'postal_code' => '06131'],
            ['zone' => 'Shan State', 'city' => 'Minekhat', 'postal_code' => '06471'],
            ['zone' => 'Shan State', 'city' => 'Minekhote', 'postal_code' => '06282'],
            ['zone' => 'Shan State', 'city' => 'Minelar', 'postal_code' => '06232'],
            ['zone' => 'Shan State', 'city' => 'Minelar', 'postal_code' => '06235'], // Minema
            ['zone' => 'Shan State', 'city' => 'Minemaw', 'postal_code' => '06521'],
            ['zone' => 'Shan State', 'city' => 'Minenaung', 'postal_code' => '06152'],
            ['zone' => 'Shan State', 'city' => 'Minepan', 'postal_code' => '06201'],
            ['zone' => 'Shan State', 'city' => 'Minephat', 'postal_code' => '06251'],
            ['zone' => 'Shan State', 'city' => 'Minepyin', 'postal_code' => '06461'], // Metman
            ['zone' => 'Shan State', 'city' => 'Minepyin', 'postal_code' => '06221'],
            ['zone' => 'Shan State', 'city' => 'Minepyin', 'postal_code' => '06222'], // Tonta
            ['zone' => 'Shan State', 'city' => 'Minesan', 'postal_code' => '06142'],
            ['zone' => 'Shan State', 'city' => 'Minesatt', 'postal_code' => '06281'],
            ['zone' => 'Shan State', 'city' => 'Mineshue', 'postal_code' => '06141'],
            ['zone' => 'Shan State', 'city' => 'Mineshue', 'postal_code' => '06142'], // Wantkan
            ['zone' => 'Shan State', 'city' => 'Mineton', 'postal_code' => '06291'],
            ['zone' => 'Shan State', 'city' => 'Mineton', 'postal_code' => '06292'], // Ponpakyin
            ['zone' => 'Shan State', 'city' => 'Mineyang', 'postal_code' => '06242'], // Minepauk
            ['zone' => 'Shan State', 'city' => 'Mineyang', 'postal_code' => '06241'],
            ['zone' => 'Shan State', 'city' => 'Mineyang', 'postal_code' => '06243'], // Seloo
            ['zone' => 'Shan State', 'city' => 'Mineyaung', 'postal_code' => '06263'], // Hotaung
            ['zone' => 'Shan State', 'city' => 'Mineyaung', 'postal_code' => '06264'], // Minewa
            ['zone' => 'Shan State', 'city' => 'Mineyaung', 'postal_code' => '06261'],
            ['zone' => 'Shan State', 'city' => 'Mineyel', 'postal_code' => '06421'],
            ['zone' => 'Shan State', 'city' => 'Mineyu', 'postal_code' => '06262'],
            ['zone' => 'Shan State', 'city' => 'Moemate', 'postal_code' => '06441'],
            ['zone' => 'Shan State', 'city' => 'Moenae\'', 'postal_code' => '06171'],
            ['zone' => 'Shan State', 'city' => 'Muse', 'postal_code' => '06402'], // Kyugoke
            ['zone' => 'Shan State', 'city' => 'Muse', 'postal_code' => '06403'], // Manheiro
            ['zone' => 'Shan State', 'city' => 'Muse', 'postal_code' => '06404'], // Monekoe
            ['zone' => 'Shan State', 'city' => 'Muse', 'postal_code' => '06401'],
            ['zone' => 'Shan State', 'city' => 'Nankham', 'postal_code' => '06412'], // Monewee
            ['zone' => 'Shan State', 'city' => 'Nankham', 'postal_code' => '06411'],
            ['zone' => 'Shan State', 'city' => 'Nantmatu', 'postal_code' => '06351'], // Bawtwin
            ['zone' => 'Shan State', 'city' => 'Nantmatu', 'postal_code' => '06352'],
            ['zone' => 'Shan State', 'city' => 'Nantsan', 'postal_code' => '06162'], // Mineseike
            ['zone' => 'Shan State', 'city' => 'Nantsan', 'postal_code' => '06161'],
            ['zone' => 'Shan State', 'city' => 'Nantsan(Ma)', 'postal_code' => '06331'],
            ['zone' => 'Shan State', 'city' => 'Narfant', 'postal_code' => '06511'], // Wyainkaung
            ['zone' => 'Shan State', 'city' => 'Naungcho', 'postal_code' => '06313'], // Kangyi
            ['zone' => 'Shan State', 'city' => 'Naungcho', 'postal_code' => '06324'], // Mainglone
            ['zone' => 'Shan State', 'city' => 'Naungcho', 'postal_code' => '06311'],
            ['zone' => 'Shan State', 'city' => 'Naungcho', 'postal_code' => '06312'], // Samsal
            ['zone' => 'Shan State', 'city' => 'Naungcho', 'postal_code' => '06314'], // Thonesel
            ['zone' => 'Shan State', 'city' => 'Naungtayar', 'postal_code' => '06053'],
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06086'], // Innhlar
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06083'], // Innpawkhon
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06088'], // Khaungtaing
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06084'], // Minethouk
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06085'], // Nanpan
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06087'], // Ngaphe'chaung
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06081'],
            ['zone' => 'Shan State', 'city' => 'Nyaungshwe', 'postal_code' => '06082'], // Ywama
            ['zone' => 'Shan State', 'city' => 'Pansan', 'postal_code' => '06491'],
            ['zone' => 'Shan State', 'city' => 'Panwinedaytha', 'postal_code' => '06501'],
            ['zone' => 'Shan State', 'city' => 'Phiekon', 'postal_code' => '06064'], // Kharatdon
            ['zone' => 'Shan State', 'city' => 'Phiekon', 'postal_code' => '06062'], // Moebywe
            ['zone' => 'Shan State', 'city' => 'Phiekon', 'postal_code' => '06061'],
            ['zone' => 'Shan State', 'city' => 'Phiekon', 'postal_code' => '06064'], // Shwepyiaye
            ['zone' => 'Shan State', 'city' => 'Pinlaung', 'postal_code' => '06051'],
            ['zone' => 'Shan State', 'city' => 'Pinlone', 'postal_code' => '06113'],
            ['zone' => 'Shan State', 'city' => 'Pinlone University', 'postal_code' => '06114'],
            ['zone' => 'Shan State', 'city' => 'Pinlong', 'postal_code' => '06052'], // Tikyit
            ['zone' => 'Shan State', 'city' => 'Pintaya', 'postal_code' => '06031'],
            ['zone' => 'Shan State', 'city' => 'Pintaya', 'postal_code' => '06032'], // Pwayhla
            ['zone' => 'Shan State', 'city' => 'Sesai', 'postal_code' => '06104'], // Banyin
            ['zone' => 'Shan State', 'city' => 'Sesai', 'postal_code' => '06102'], // Naungmon
            ['zone' => 'Shan State', 'city' => 'Sesai', 'postal_code' => '06105'], // Naungtaw
            ['zone' => 'Shan State', 'city' => 'Sesai', 'postal_code' => '06103'], // Saikekhaung
            ['zone' => 'Shan State', 'city' => 'Sesai', 'postal_code' => '06101'],
            ['zone' => 'Shan State', 'city' => 'Tachileik', 'postal_code' => '06271'],
            ['zone' => 'Shan State', 'city' => 'Tantyan', 'postal_code' => '06431'],
            ['zone' => 'Shan State', 'city' => 'Tarlay', 'postal_code' => '06272'],
            ['zone' => 'Shan State', 'city' => 'Taunggyi', 'postal_code' => '06014'], // Ayethaya
            ['zone' => 'Shan State', 'city' => 'Taunggyi', 'postal_code' => '06015'], // GTU
            ['zone' => 'Shan State', 'city' => 'Taunggyi', 'postal_code' => '06012'], // Shwenyaung
            ['zone' => 'Shan State', 'city' => 'Taunggyi', 'postal_code' => '06011'],
            ['zone' => 'Shan State', 'city' => 'Taunggyi University', 'postal_code' => '06013'],
            ['zone' => 'Shan State', 'city' => 'Taunggyi', 'postal_code' => '06018'], // Taungni
            ['zone' => 'Shan State', 'city' => 'Theinni', 'postal_code' => '06361'],
            ['zone' => 'Shan State', 'city' => 'Thipal', 'postal_code' => '06342'], // Nantlan
            ['zone' => 'Shan State', 'city' => 'Thipal', 'postal_code' => '06343'], // Sinkyawt
            ['zone' => 'Shan State', 'city' => 'Thipaw', 'postal_code' => '06341'],
            ['zone' => 'Shan State', 'city' => 'Yatsauk', 'postal_code' => '06074'], // Pinphit
            ['zone' => 'Shan State', 'city' => 'Yatsauk', 'postal_code' => '06071'],
            ['zone' => 'Shan State', 'city' => 'Yatsouth', 'postal_code' => '06072'], // Bahtoo
            ['zone' => 'Shan State', 'city' => 'Ywarngan', 'postal_code' => '06042'], // Myinkyadoe
            ['zone' => 'Shan State', 'city' => 'Ywarngan', 'postal_code' => '06043'], // YeiOo
            ['zone' => 'Shan State', 'city' => 'Ywarngan', 'postal_code' => '06041'],

            // RAKHINE STATE
            ['zone' => 'Rakhine State', 'city' => 'Ann', 'postal_code' => '07151'],
            ['zone' => 'Rakhine State', 'city' => 'Tattaung', 'postal_code' => '07152'],
            ['zone' => 'Rakhine State', 'city' => 'Buthidaung', 'postal_code' => '07031'],
            ['zone' => 'Rakhine State', 'city' => 'Ponnyolate', 'postal_code' => '07033'],
            ['zone' => 'Rakhine State', 'city' => 'Kahtila', 'postal_code' => '07034'],
            ['zone' => 'Rakhine State', 'city' => 'Kyauksating', 'postal_code' => '07035'],
            ['zone' => 'Rakhine State', 'city' => 'Tharaphe', 'postal_code' => '07036'],
            ['zone' => 'Rakhine State', 'city' => 'Nyaungchaung', 'postal_code' => '07037'],
            ['zone' => 'Rakhine State', 'city' => 'Gwa', 'postal_code' => '07181'],
            ['zone' => 'Rakhine State', 'city' => 'Kyeintali', 'postal_code' => '07182'],
            ['zone' => 'Rakhine State', 'city' => 'Sattwar', 'postal_code' => '07183'],
            ['zone' => 'Rakhine State', 'city' => 'Kanthaya', 'postal_code' => '07184'],
            ['zone' => 'Rakhine State', 'city' => 'Kyaukphyu', 'postal_code' => '07121'],
            ['zone' => 'Rakhine State', 'city' => 'Sanae\'', 'postal_code' => '07122'],
            ['zone' => 'Rakhine State', 'city' => 'Zinchaung', 'postal_code' => '07123'],
            ['zone' => 'Rakhine State', 'city' => 'Kyauktaw', 'postal_code' => '07061'],
            ['zone' => 'Rakhine State', 'city' => 'Apaukwa', 'postal_code' => '07062'],
            ['zone' => 'Rakhine State', 'city' => 'Kansouth', 'postal_code' => '07063'],
            ['zone' => 'Rakhine State', 'city' => 'Thitpon', 'postal_code' => '07142'],
            ['zone' => 'Rakhine State', 'city' => 'Mamaung', 'postal_code' => '07141'],
            ['zone' => 'Rakhine State', 'city' => 'Maungdaw', 'postal_code' => '07021'],
            ['zone' => 'Rakhine State', 'city' => 'Kyainchaung', 'postal_code' => '07192'],
            ['zone' => 'Rakhine State', 'city' => 'Ngakhuya', 'postal_code' => '07022'],
            ['zone' => 'Rakhine State', 'city' => 'Taungpyowae\'', 'postal_code' => '07191'],
            ['zone' => 'Rakhine State', 'city' => 'Ahlaethankyaw', 'postal_code' => '07023'],
            ['zone' => 'Rakhine State', 'city' => 'Aungthapyay', 'postal_code' => '07024'],
            ['zone' => 'Rakhine State', 'city' => 'Yemyettaung', 'postal_code' => '07025'],
            ['zone' => 'Rakhine State', 'city' => 'Kyaukpantu', 'postal_code' => '07026'],
            ['zone' => 'Rakhine State', 'city' => 'Minkhamaung', 'postal_code' => '07027'],
            ['zone' => 'Rakhine State', 'city' => 'Mingalarnyunt', 'postal_code' => '07028'],
            ['zone' => 'Rakhine State', 'city' => 'Mingalargyi', 'postal_code' => '07029'],
            ['zone' => 'Rakhine State', 'city' => 'Tamanthar', 'postal_code' => '07193'],
            ['zone' => 'Rakhine State', 'city' => 'Kintaung', 'postal_code' => '07194'],
            ['zone' => 'Rakhine State', 'city' => 'Minbya', 'postal_code' => '07091'],
            ['zone' => 'Rakhine State', 'city' => 'Kanni', 'postal_code' => '07094'],
            ['zone' => 'Rakhine State', 'city' => 'MyaukOo', 'postal_code' => '07101'],
            ['zone' => 'Rakhine State', 'city' => 'Tainnyo', 'postal_code' => '07102'],
            ['zone' => 'Rakhine State', 'city' => 'Myaungbwe', 'postal_code' => '07092'],
            ['zone' => 'Rakhine State', 'city' => 'Myepon', 'postal_code' => '07111'],
            ['zone' => 'Rakhine State', 'city' => 'Paletwa', 'postal_code' => '07071'],
            ['zone' => 'Rakhine State', 'city' => 'Panmyaung', 'postal_code' => '07093'],
            ['zone' => 'Rakhine State', 'city' => 'Pauktaw', 'postal_code' => '07081'],
            ['zone' => 'Rakhine State', 'city' => 'Ponnagyun', 'postal_code' => '07051'],
            ['zone' => 'Rakhine State', 'city' => 'Yotayoke', 'postal_code' => '07052'],
            ['zone' => 'Rakhine State', 'city' => 'Thetat', 'postal_code' => '07053'],
            ['zone' => 'Rakhine State', 'city' => 'Poesheepyin', 'postal_code' => '07054'],
            ['zone' => 'Rakhine State', 'city' => 'Rambree', 'postal_code' => '07131'],
            ['zone' => 'Rakhine State', 'city' => 'Kyauknimaw', 'postal_code' => '07132'],
            ['zone' => 'Rakhine State', 'city' => 'Rathedaung', 'postal_code' => '07041'],
            ['zone' => 'Rakhine State', 'city' => 'Zaydipyin', 'postal_code' => '07032'],
            ['zone' => 'Rakhine State', 'city' => 'Ahngumaw', 'postal_code' => '07042'],
            ['zone' => 'Rakhine State', 'city' => 'Sittwe', 'postal_code' => '07011'],
            ['zone' => 'Rakhine State', 'city' => 'Sittwe Cantoment', 'postal_code' => '07012'],
            ['zone' => 'Rakhine State', 'city' => 'Mingan', 'postal_code' => '07014'],
            ['zone' => 'Rakhine State', 'city' => 'Rupa', 'postal_code' => '07013'],
            ['zone' => 'Rakhine State', 'city' => 'Thatkaypyin', 'postal_code' => '07015'],
            ['zone' => 'Rakhine State', 'city' => 'Taunggoke', 'postal_code' => '07161'],
            ['zone' => 'Rakhine State', 'city' => 'Maei', 'postal_code' => '07162'],
            ['zone' => 'Rakhine State', 'city' => 'Ywama', 'postal_code' => '07163'],
            ['zone' => 'Rakhine State', 'city' => 'Lamu', 'postal_code' => '07164'],
            ['zone' => 'Rakhine State', 'city' => 'Ngapali', 'postal_code' => '07172'],
            ['zone' => 'Rakhine State', 'city' => 'Kinmaw', 'postal_code' => '07173'],
            ['zone' => 'Rakhine State', 'city' => 'Pazunphay', 'postal_code' => '07174'],
            ['zone' => 'Rakhine State', 'city' => 'Thantwe', 'postal_code' => '07171'],

            // BAGO REGION
            ['zone' => 'Bago Region', 'city' => 'Bago', 'postal_code' => '08011'],
            ['zone' => 'Bago Region', 'city' => 'Bago Collage', 'postal_code' => '08018'],
            ['zone' => 'Bago Region', 'city' => 'Oakthamyothit', 'postal_code' => '08017'],
            ['zone' => 'Bago Region', 'city' => 'Phayagyi', 'postal_code' => '08013'],
            ['zone' => 'Bago Region', 'city' => 'Inntakaw', 'postal_code' => '08016'],
            ['zone' => 'Bago Region', 'city' => 'Htongyi', 'postal_code' => '08015'],
            ['zone' => 'Bago Region', 'city' => 'Pyinpongyi', 'postal_code' => '08012'],
            ['zone' => 'Bago Region', 'city' => 'Kyauktan', 'postal_code' => '08014'],
            ['zone' => 'Bago Region', 'city' => 'Thayaaye', 'postal_code' => '08019'],
            ['zone' => 'Bago Region', 'city' => 'Katoke', 'postal_code' => '08063'],
            ['zone' => 'Bago Region', 'city' => 'Tarwayedagar', 'postal_code' => '08084'],
            ['zone' => 'Bago Region', 'city' => 'Deiku', 'postal_code' => '08061'],
            ['zone' => 'Bago Region', 'city' => 'Phaungdawthi', 'postal_code' => '08062'],
            ['zone' => 'Bago Region', 'city' => 'Ayethukha', 'postal_code' => '08064'],
            ['zone' => 'Bago Region', 'city' => 'Gyobingauk', 'postal_code' => '08231'],
            ['zone' => 'Bago Region', 'city' => 'Htantabin', 'postal_code' => '08131'],
            ['zone' => 'Bago Region', 'city' => 'Zayatgyi', 'postal_code' => '08132'],
            ['zone' => 'Bago Region', 'city' => 'Kawa', 'postal_code' => '08091'],
            ['zone' => 'Bago Region', 'city' => 'Thatgala', 'postal_code' => '08094'],
            ['zone' => 'Bago Region', 'city' => 'Ohnnhe', 'postal_code' => '08093'],
            ['zone' => 'Bago Region', 'city' => 'Kyaukgyi', 'postal_code' => '08041'],
            ['zone' => 'Bago Region', 'city' => 'Natthankwin', 'postal_code' => '08042'],
            ['zone' => 'Bago Region', 'city' => 'Mone', 'postal_code' => '08143'],
            ['zone' => 'Bago Region', 'city' => 'Kyauktagar', 'postal_code' => '08021'],
            ['zone' => 'Bago Region', 'city' => 'Penwegone', 'postal_code' => '08023'],
            ['zone' => 'Bago Region', 'city' => 'Phado', 'postal_code' => '08024'],
            ['zone' => 'Bago Region', 'city' => 'Tawkyweinn', 'postal_code' => '08022'],
            ['zone' => 'Bago Region', 'city' => 'Thahtaygone', 'postal_code' => '08025'],
            ['zone' => 'Bago Region', 'city' => 'Letpadan', 'postal_code' => '08271'],
            ['zone' => 'Bago Region', 'city' => 'Tharawaw', 'postal_code' => '08273'],
            ['zone' => 'Bago Region', 'city' => 'Zeephyugone', 'postal_code' => '08272'],
            ['zone' => 'Bago Region', 'city' => 'Khamonsake', 'postal_code' => '08274'],
            ['zone' => 'Bago Region', 'city' => 'Minhla', 'postal_code' => '08261'],
            ['zone' => 'Bago Region', 'city' => 'Sitkwin', 'postal_code' => '08262'],
            ['zone' => 'Bago Region', 'city' => 'Moenyo', 'postal_code' => '08241'],
            ['zone' => 'Bago Region', 'city' => 'Htaintaw', 'postal_code' => '08243'],
            ['zone' => 'Bago Region', 'city' => 'Yaekin', 'postal_code' => '08242'],
            ['zone' => 'Bago Region', 'city' => 'Pathtaw', 'postal_code' => '08244'],
            ['zone' => 'Bago Region', 'city' => 'Nattalin', 'postal_code' => '08211'],
            ['zone' => 'Bago Region', 'city' => 'Tarpon', 'postal_code' => '08212'],
            ['zone' => 'Bago Region', 'city' => 'Taungnyo', 'postal_code' => '08213'],
            ['zone' => 'Bago Region', 'city' => 'Damange', 'postal_code' => '08214'],
            ['zone' => 'Bago Region', 'city' => 'Nyaunglaybin', 'postal_code' => '08031'],
            ['zone' => 'Bago Region', 'city' => 'Painzalote', 'postal_code' => '08032'],
            ['zone' => 'Bago Region', 'city' => 'Pyuntansar', 'postal_code' => '08034'],
            ['zone' => 'Bago Region', 'city' => 'Oakpho', 'postal_code' => '08251'],
            ['zone' => 'Bago Region', 'city' => 'Ayemyathayar', 'postal_code' => '08253'],
            ['zone' => 'Bago Region', 'city' => 'O-Thegone', 'postal_code' => '08252'],
            ['zone' => 'Bago Region', 'city' => 'Oaktwin', 'postal_code' => '08121'],
            ['zone' => 'Bago Region', 'city' => 'Kywebwe', 'postal_code' => '08122'],
            ['zone' => 'Bago Region', 'city' => 'Nyaungchayhtut', 'postal_code' => '08123'],
            ['zone' => 'Bago Region', 'city' => 'Padaung', 'postal_code' => '08171'],
            ['zone' => 'Bago Region', 'city' => 'Hsinde', 'postal_code' => '08174'],
            ['zone' => 'Bago Region', 'city' => 'Htone Bo', 'postal_code' => '08173'],
            ['zone' => 'Bago Region', 'city' => 'Kwinhla', 'postal_code' => '08176'],
            ['zone' => 'Bago Region', 'city' => 'Oakshitbyin', 'postal_code' => '08175'],
            ['zone' => 'Bago Region', 'city' => 'Thuyetan', 'postal_code' => '08172'],
            ['zone' => 'Bago Region', 'city' => 'Paukkhaung', 'postal_code' => '08161'],
            ['zone' => 'Bago Region', 'city' => 'Paungde', 'postal_code' => '08201'],
            ['zone' => 'Bago Region', 'city' => 'Hmattaing', 'postal_code' => '08202'],
            ['zone' => 'Bago Region', 'city' => 'Thafangone', 'postal_code' => '08203'],
            ['zone' => 'Bago Region', 'city' => 'Phyu', 'postal_code' => '08141'],
            ['zone' => 'Bago Region', 'city' => 'Kannyuntkwin', 'postal_code' => '08145'],
            ['zone' => 'Bago Region', 'city' => 'Zayyawadi', 'postal_code' => '08142'],
            ['zone' => 'Bago Region', 'city' => 'Nyaungbintha', 'postal_code' => '08144'],
            ['zone' => 'Bago Region', 'city' => 'Pyay', 'postal_code' => '08151'],
            ['zone' => 'Bago Region', 'city' => 'Wethteekan', 'postal_code' => '08155'],
            ['zone' => 'Bago Region', 'city' => 'Paungdale', 'postal_code' => '08154'],
            ['zone' => 'Bago Region', 'city' => 'Pyay University', 'postal_code' => '08156'],
            ['zone' => 'Bago Region', 'city' => 'Khittayar Myothit', 'postal_code' => '08152'],
            ['zone' => 'Bago Region', 'city' => 'Hmawzar', 'postal_code' => '08153'],
            ['zone' => 'Bago Region', 'city' => 'Shwedaung', 'postal_code' => '08181'],
            ['zone' => 'Bago Region', 'city' => 'Kyeethe', 'postal_code' => '08182'],
            ['zone' => 'Bago Region', 'city' => 'Tayokehmaw', 'postal_code' => '08183'],
            ['zone' => 'Bago Region', 'city' => 'Shwekyin', 'postal_code' => '08051'],
            ['zone' => 'Bago Region', 'city' => 'Madauk', 'postal_code' => '08033'],
            ['zone' => 'Bago Region', 'city' => 'Taungoo', 'postal_code' => '08101'],
            ['zone' => 'Bago Region', 'city' => 'Kaytumadi', 'postal_code' => '08104'],
            ['zone' => 'Bago Region', 'city' => 'Kyaetaw', 'postal_code' => '08103'],
            ['zone' => 'Bago Region', 'city' => 'TaungooUniversity', 'postal_code' => '08105'],
            ['zone' => 'Bago Region', 'city' => 'Thanapin', 'postal_code' => '08081'],
            ['zone' => 'Bago Region', 'city' => 'Yitkangyi', 'postal_code' => '08092'],
            ['zone' => 'Bago Region', 'city' => 'Kamasae\'', 'postal_code' => '08083'],
            ['zone' => 'Bago Region', 'city' => 'Kyungyi', 'postal_code' => '08085'],
            ['zone' => 'Bago Region', 'city' => 'Minywa', 'postal_code' => '08082'],
            ['zone' => 'Bago Region', 'city' => 'Kalarchaunggyi', 'postal_code' => '08086'],
            ['zone' => 'Bago Region', 'city' => 'Tharrawaddy', 'postal_code' => '08281'],
            ['zone' => 'Bago Region', 'city' => 'Thoneze', 'postal_code' => '08282'],
            ['zone' => 'Bago Region', 'city' => 'Sanyawe', 'postal_code' => '08232'],
            ['zone' => 'Bago Region', 'city' => 'Thegone', 'postal_code' => '08191'],
            ['zone' => 'Bago Region', 'city' => 'Padegone', 'postal_code' => '08193'],
            ['zone' => 'Bago Region', 'city' => 'Sinhmeeswe', 'postal_code' => '08192'],
            ['zone' => 'Bago Region', 'city' => 'Innma', 'postal_code' => '08194'],
            ['zone' => 'Bago Region', 'city' => 'Wetpoke', 'postal_code' => '08195'],
            ['zone' => 'Bago Region', 'city' => 'Waw', 'postal_code' => '08071'],
            ['zone' => 'Bago Region', 'city' => 'Nyaungkharshe', 'postal_code' => '08072'],
            ['zone' => 'Bago Region', 'city' => 'Thuyethamain', 'postal_code' => '08073'],
            ['zone' => 'Bago Region', 'city' => 'Myitkyo', 'postal_code' => '08074'],
            ['zone' => 'Bago Region', 'city' => 'Yedashe', 'postal_code' => '08111'],
            ['zone' => 'Bago Region', 'city' => 'Swa', 'postal_code' => '08115'],
            ['zone' => 'Bago Region', 'city' => 'Yeni', 'postal_code' => '08112'],
            ['zone' => 'Bago Region', 'city' => 'Myohla', 'postal_code' => '08113'],
            ['zone' => 'Bago Region', 'city' => 'Thagaya', 'postal_code' => '08114'],
            ['zone' => 'Bago Region', 'city' => 'Laymyethnar', 'postal_code' => '08222'],
            ['zone' => 'Bago Region', 'city' => 'Zeegone', 'postal_code' => '08221'],

            // KAYAH STATE
            ['zone' => 'Kayah State', 'city' => 'Loikaw', 'postal_code' => '09011'],
            ['zone' => 'Kayah State', 'city' => 'Bawlakhe', 'postal_code' => '09041'],
            ['zone' => 'Kayah State', 'city' => 'Shartaw', 'postal_code' => '09071'],
            ['zone' => 'Kayah State', 'city' => 'Phasaung', 'postal_code' => '09051'],
            ['zone' => 'Kayah State', 'city' => 'Demohso', 'postal_code' => '09021'],
            ['zone' => 'Kayah State', 'city' => 'Lawpita', 'postal_code' => '09012'],
            ['zone' => 'Kayah State', 'city' => 'Pharuso', 'postal_code' => '09031'],
            ['zone' => 'Kayah State', 'city' => 'Dawtamagyi', 'postal_code' => '09022'],
            ['zone' => 'Kayah State', 'city' => 'Pekin', 'postal_code' => '09081'],
            ['zone' => 'Kayah State', 'city' => 'Ywa Thit', 'postal_code' => '09042'],
            ['zone' => 'Kayah State', 'city' => 'Mawchee', 'postal_code' => '09052'],
            ['zone' => 'Kayah State', 'city' => 'Meisei', 'postal_code' => '09061'],
            ['zone' => 'Kayah State', 'city' => 'Loikaw University', 'postal_code' => '09013'],
            ['zone' => 'Kayah State', 'city' => 'Loilenlay', 'postal_code' => '09014'],

            // AYEYARWADY REGION
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pathein', 'postal_code' => '10011'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Hinthada', 'postal_code' => '10061'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Maubin', 'postal_code' => '10181'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Myaungmya', 'postal_code' => '10211'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Warkema', 'postal_code' => '10201'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pyapon', 'postal_code' => '10251'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Thoneminemyothit', 'postal_code' => '10122'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'PatheinCantonment', 'postal_code' => '10012'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kangyidaung', 'postal_code' => '10021'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Myetto', 'postal_code' => '10013'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Thabaung', 'postal_code' => '10111'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ngaputaw', 'postal_code' => '10131'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyonepyaw', 'postal_code' => '10091'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ahthoke', 'postal_code' => '10082'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyaunggone', 'postal_code' => '10101'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Laymyethnar', 'postal_code' => '10071'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kanaung', 'postal_code' => '10042'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Batye', 'postal_code' => '10032'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ingabu', 'postal_code' => '10051'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Htugyi', 'postal_code' => '10052'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Mezalegone', 'postal_code' => '10053'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Nyaungtone', 'postal_code' => '10161'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Dedaye', 'postal_code' => '10261'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyonmange', 'postal_code' => '10202'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Zalun', 'postal_code' => '10141'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pathein University', 'postal_code' => '10014'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ngathaingchaung', 'postal_code' => '10291'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'B.E.D', 'postal_code' => '10016'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Chaungtha', 'postal_code' => '10282'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pyinkhayaing', 'postal_code' => '10322'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Hainggyi', 'postal_code' => '10321'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Yekyi', 'postal_code' => '10081'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Dambi', 'postal_code' => '10062'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Myanaung', 'postal_code' => '10041'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyankhin', 'postal_code' => '10031'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Einme', 'postal_code' => '10191'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Shwelaung', 'postal_code' => '10203'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Mawlamyainggyun', 'postal_code' => '10221'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pantanaw', 'postal_code' => '10171'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Danubyu', 'postal_code' => '10151'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Zakargyi', 'postal_code' => '10152'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Bogalay', 'postal_code' => '10231'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyaiklat', 'postal_code' => '10241'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Labutta', 'postal_code' => '10121'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pathein Shipyard', 'postal_code' => '10015'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ngwesaung', 'postal_code' => '10271'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Daka', 'postal_code' => '10022'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Thaunggyi', 'postal_code' => '10093'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ahhtaung', 'postal_code' => '10092'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ngayokekaung', 'postal_code' => '10301'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Shwethaungyan', 'postal_code' => '10281'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ahmar', 'postal_code' => '10311'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Thidakongpyin', 'postal_code' => '10083'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ngapiseik', 'postal_code' => '10084'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'HinthadaUniversity', 'postal_code' => '10063'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Daunggyi', 'postal_code' => '10142'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ngapiseik', 'postal_code' => '10044'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Innbin', 'postal_code' => '10043'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kwingauk', 'postal_code' => '10054'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Nyaungkyo', 'postal_code' => '10055'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pyinywa', 'postal_code' => '10212'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Jute Factory', 'postal_code' => '10213'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Hlaingbone', 'postal_code' => '10122'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Yelaekalay', 'postal_code' => '10183'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Maubin University', 'postal_code' => '10184'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Shwetaunghmaw', 'postal_code' => '10182'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyonekadon', 'postal_code' => '10252'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kadonkane', 'postal_code' => '10233'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'G.T.C (Pathein)', 'postal_code' => '10017'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'G.C.C (Pathein)', 'postal_code' => '10018'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Pyinsalu', 'postal_code' => '10331'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'G.T.C (Hinthada)', 'postal_code' => '10064'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyonekuu', 'postal_code' => '10323'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Myinkakone', 'postal_code' => '10232'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyitha', 'postal_code' => '10019'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kanywa', 'postal_code' => '10023'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Phayargone', 'postal_code' => '10112'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Chaungwa', 'postal_code' => '10324'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Zayathla', 'postal_code' => '10085'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Yodayartet', 'postal_code' => '10086'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Nateban', 'postal_code' => '10065'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Nathmaw', 'postal_code' => '10066'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Phayargone', 'postal_code' => '10067'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Yonethalin', 'postal_code' => '10068'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Sagarmyar', 'postal_code' => '10215'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Ai Tha Byu', 'postal_code' => '10072'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Khamoutsu', 'postal_code' => '10073'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Shwekyin', 'postal_code' => '10045'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Zaungtan', 'postal_code' => '10056'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Chaukywar', 'postal_code' => '10057'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyarkan', 'postal_code' => '10125'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Yetwinyekan', 'postal_code' => '10214'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Sharkhe', 'postal_code' => '10069'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kanbat', 'postal_code' => '10124'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Betutkalay', 'postal_code' => '10123'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyungone', 'postal_code' => '10204'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyeikpi', 'postal_code' => '10223'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kywe Done', 'postal_code' => '10187'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Layainzu', 'postal_code' => '10188'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyonesoke', 'postal_code' => '10185'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Sitchaung', 'postal_code' => '10186'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Daunggyi', 'postal_code' => '10172'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Sarmalout', 'postal_code' => '10164'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Mezale', 'postal_code' => '10163'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Chaunggyi', 'postal_code' => '10162'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Sankin', 'postal_code' => '10154'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyonetanee', 'postal_code' => '10153'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Kyatphamhwezoung', 'postal_code' => '10254'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Thamainhtaw', 'postal_code' => '10253'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Yonedaunt', 'postal_code' => '10242'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Suukalap', 'postal_code' => '10262'],
            ['zone' => 'Ayeyarwady Region', 'city' => 'Sinma', 'postal_code' => '10272'],

            // YANGON REGION (from YANGON DIVISION)
            ['zone' => 'Yangon', 'city' => 'Ahlone', 'postal_code' => '11121'],
            ['zone' => 'Yangon', 'city' => 'Aung San', 'postal_code' => '11012'],
            ['zone' => 'Yangon', 'city' => 'Bahan', 'postal_code' => '11201'],
            ['zone' => 'Yangon', 'city' => 'Bayintnaung Market (Thamine)', 'postal_code' => '11062'],
            ['zone' => 'Yangon', 'city' => 'Bogyoke Market', 'postal_code' => '11143'],
            ['zone' => 'Yangon', 'city' => 'Botahtaung', 'postal_code' => '11162'],
            ['zone' => 'Yangon', 'city' => 'Botahtaung', 'postal_code' => '11161'],
            ['zone' => 'Yangon', 'city' => 'Dagon', 'postal_code' => '11191'],
            ['zone' => 'Yangon', 'city' => 'Dagon Myothit (North)', 'postal_code' => '11421'],
            ['zone' => 'Yangon', 'city' => 'Dagon Myothit (South)', 'postal_code' => '11431'],
            ['zone' => 'Yangon', 'city' => 'Dawbon', 'postal_code' => '11241'],
            ['zone' => 'Yangon', 'city' => 'Hlaing', 'postal_code' => '11051'],
            ['zone' => 'Yangon', 'city' => 'Hlaing Thar Yar', 'postal_code' => '11401'],
            ['zone' => 'Yangon', 'city' => 'Insein', 'postal_code' => '11011'],
            ['zone' => 'Yangon', 'city' => 'Kaba Aye', 'postal_code' => '11061'],
            ['zone' => 'Yangon', 'city' => 'Kamayut', 'postal_code' => '11041'],
            ['zone' => 'Yangon', 'city' => 'Kyauk Tan', 'postal_code' => '11301'],
            ['zone' => 'Yangon', 'city' => 'Kyauktada', 'postal_code' => '11182'],
            ['zone' => 'Yangon', 'city' => 'Kyeemyindaing', 'postal_code' => '11101'],
            ['zone' => 'Yangon', 'city' => 'Lanmadaw', 'postal_code' => '11131'],
            ['zone' => 'Yangon', 'city' => 'Mingalar Taung Nyunt', 'postal_code' => '11221'],
            ['zone' => 'Yangon', 'city' => 'Mingalardon', 'postal_code' => '11021'],
            ['zone' => 'Yangon', 'city' => 'Okkalapa (North)', 'postal_code' => '11031'],
            ['zone' => 'Yangon', 'city' => 'Okkalapa (South)', 'postal_code' => '11091'],
            ['zone' => 'Yangon', 'city' => 'Pabedan', 'postal_code' => '11141'],
            ['zone' => 'Yangon', 'city' => 'Pazundaung', 'postal_code' => '11171'],
            ['zone' => 'Yangon', 'city' => 'Pyi Thar Yar', 'postal_code' => '11082'],
            ['zone' => 'Yangon', 'city' => 'Sanchaung', 'postal_code' => '11111'],
            ['zone' => 'Yangon', 'city' => 'Shwe Pyi Thar', 'postal_code' => '11411'],
            ['zone' => 'Yangon', 'city' => 'Shwepaukan', 'postal_code' => '11032'],
            ['zone' => 'Yangon', 'city' => 'Tamwe', 'postal_code' => '11211'],
            ['zone' => 'Yangon', 'city' => 'Tanyin', 'postal_code' => '11291'],
            ['zone' => 'Yangon', 'city' => 'Thamine College', 'postal_code' => '11052'],
            ['zone' => 'Yangon', 'city' => 'Tharkayta', 'postal_code' => '11231'],
            ['zone' => 'Yangon', 'city' => 'Theingyi Market', 'postal_code' => '11142'],
            ['zone' => 'Yangon', 'city' => 'Thingangyun', 'postal_code' => '11071'],
            ['zone' => 'Yangon', 'city' => 'Thuwunna', 'postal_code' => '11072'],
            ['zone' => 'Yangon', 'city' => 'Yangon', 'postal_code' => '11181'],
            ['zone' => 'Yangon', 'city' => 'Yangon Station', 'postal_code' => '11222'],
            ['zone' => 'Yangon', 'city' => 'Yankin', 'postal_code' => '11081'],

            // MON STATE
            ['zone' => 'Mon State', 'city' => 'Beelin', 'postal_code' => '12031'],
            ['zone' => 'Mon State', 'city' => 'Taungzon', 'postal_code' => '12032'],
            ['zone' => 'Mon State', 'city' => 'Chaungsone', 'postal_code' => '12061'],
            ['zone' => 'Mon State', 'city' => 'Ywalut', 'postal_code' => '12062'],
            ['zone' => 'Mon State', 'city' => 'Kalwi', 'postal_code' => '12063'],
            ['zone' => 'Mon State', 'city' => 'Muyitkalay', 'postal_code' => '12064'],
            ['zone' => 'Mon State', 'city' => 'Kyaikhto', 'postal_code' => '12021'],
            ['zone' => 'Mon State', 'city' => 'Theinzayet', 'postal_code' => '12022'],
            ['zone' => 'Mon State', 'city' => 'Kyaikmaraw', 'postal_code' => '12071'],
            ['zone' => 'Mon State', 'city' => 'Nyaungbinseik', 'postal_code' => '12072'],
            ['zone' => 'Mon State', 'city' => 'Kyeikhteoyoyinpyin', 'postal_code' => '12024'],
            ['zone' => 'Mon State', 'city' => 'Mokepalin', 'postal_code' => '12023'],
            ['zone' => 'Mon State', 'city' => 'Sittaung', 'postal_code' => '12026'],
            ['zone' => 'Mon State', 'city' => 'Mayangone', 'postal_code' => '12025'],
            ['zone' => 'Mon State', 'city' => 'Kyeikkatha', 'postal_code' => '12027'],
            ['zone' => 'Mon State', 'city' => 'Kyeikkatha', 'postal_code' => '12027'],
            ['zone' => 'Mon State', 'city' => 'Kyeikmayaw', 'postal_code' => '12073'],
            ['zone' => 'Mon State', 'city' => 'Chaungnagwa', 'postal_code' => '12074'],
            ['zone' => 'Mon State', 'city' => 'Mawlamyaing', 'postal_code' => '12011'],
            ['zone' => 'Mon State', 'city' => 'Mawlamyaing University', 'postal_code' => '12012'],
            ['zone' => 'Mon State', 'city' => 'Daweizu', 'postal_code' => '12015'],
            ['zone' => 'Mon State', 'city' => 'Daingwunkwin', 'postal_code' => '12014'],
            ['zone' => 'Mon State', 'city' => 'Mupon', 'postal_code' => '12013'],
            ['zone' => 'Mon State', 'city' => 'Zayyathiri', 'postal_code' => '12017'],
            ['zone' => 'Mon State', 'city' => 'Myaingthaya', 'postal_code' => '12016'],
            ['zone' => 'Mon State', 'city' => 'Kadoe', 'postal_code' => '12018'],
            ['zone' => 'Mon State', 'city' => 'Mudon', 'postal_code' => '12081'],
            ['zone' => 'Mon State', 'city' => 'Nattaung', 'postal_code' => '12082'],
            ['zone' => 'Mon State', 'city' => 'Kamawet', 'postal_code' => '12084'],
            ['zone' => 'Mon State', 'city' => 'Kaloutthaut', 'postal_code' => '12085'],
            ['zone' => 'Mon State', 'city' => 'Hpaout', 'postal_code' => '12083'],
            ['zone' => 'Mon State', 'city' => 'Paung', 'postal_code' => '12051'],
            ['zone' => 'Mon State', 'city' => 'Mottama', 'postal_code' => '12052'],
            ['zone' => 'Mon State', 'city' => 'Yinnyein', 'postal_code' => '12054'],
            ['zone' => 'Mon State', 'city' => 'Zinkyeik', 'postal_code' => '12053'],
            ['zone' => 'Mon State', 'city' => 'Kywechan', 'postal_code' => '12055'],
            ['zone' => 'Mon State', 'city' => 'Ahhlat', 'postal_code' => '12056'],
            ['zone' => 'Mon State', 'city' => 'Thahton', 'postal_code' => '12041'],
            ['zone' => 'Mon State', 'city' => 'Theinseik', 'postal_code' => '12042'],
            ['zone' => 'Mon State', 'city' => 'Thutdamawaddy', 'postal_code' => '12043'],
            ['zone' => 'Mon State', 'city' => 'Thanbyuzayet', 'postal_code' => '12091'],
            ['zone' => 'Mon State', 'city' => 'Panga', 'postal_code' => '12094'],
            ['zone' => 'Mon State', 'city' => 'Wegali', 'postal_code' => '12093'],
            ['zone' => 'Mon State', 'city' => 'Kyonkadat', 'postal_code' => '12095'],
            ['zone' => 'Mon State', 'city' => 'Kyaikkhame', 'postal_code' => '12092'],
            ['zone' => 'Mon State', 'city' => 'Ye', 'postal_code' => '12101'],
            ['zone' => 'Mon State', 'city' => 'Lamine', 'postal_code' => '12102'],
            ['zone' => 'Mon State', 'city' => 'Khawza', 'postal_code' => '12104'],
            ['zone' => 'Mon State', 'city' => 'Ahsin', 'postal_code' => '12103'],
            ['zone' => 'Mon State', 'city' => 'Hnitkayin', 'postal_code' => '12105'],
            ['zone' => 'Mon State', 'city' => 'Kyaungywa', 'postal_code' => '12106'],

            // KAYIN STATE
            ['zone' => 'Kayin State', 'city' => 'Hpaan', 'postal_code' => '13011'],
            ['zone' => 'Kayin State', 'city' => 'Kawkareit', 'postal_code' => '13061'],
            ['zone' => 'Kayin State', 'city' => 'Myawaddy', 'postal_code' => '13051'],
            ['zone' => 'Kayin State', 'city' => 'Thantaungthit', 'postal_code' => '13021'],
            ['zone' => 'Kayin State', 'city' => 'Hlainebwe', 'postal_code' => '13041'],
            ['zone' => 'Kayin State', 'city' => 'Hpapun', 'postal_code' => '13031'],
            ['zone' => 'Kayin State', 'city' => 'Kyarinseikkyi', 'postal_code' => '13071'],
            ['zone' => 'Kayin State', 'city' => 'Thantaunggyi', 'postal_code' => '13022'],
            ['zone' => 'Kayin State', 'city' => 'Shwegwan', 'postal_code' => '13042'],
            ['zone' => 'Kayin State', 'city' => 'Myaing Gyi Ngu', 'postal_code' => '13043'],
            ['zone' => 'Kayin State', 'city' => 'Paingkyon', 'postal_code' => '13044'],
            ['zone' => 'Kayin State', 'city' => 'Zarthapyin', 'postal_code' => '13013'],
            ['zone' => 'Kayin State', 'city' => 'Htonaing', 'postal_code' => '13012'],
            ['zone' => 'Kayin State', 'city' => 'Myaingkalay', 'postal_code' => '13014'],
            ['zone' => 'Kayin State', 'city' => 'Eindu', 'postal_code' => '13015'],
            ['zone' => 'Kayin State', 'city' => 'Tayokehla', 'postal_code' => '13016'],
            ['zone' => 'Kayin State', 'city' => 'Hpaan University', 'postal_code' => '13017'],
            ['zone' => 'Kayin State', 'city' => 'Kamamaung', 'postal_code' => '13032'],
            ['zone' => 'Kayin State', 'city' => 'Kyondo', 'postal_code' => '13062'],
            ['zone' => 'Kayin State', 'city' => 'Nabu', 'postal_code' => '13064'],
            ['zone' => 'Kayin State', 'city' => 'Kawtbain', 'postal_code' => '13063'],
            ['zone' => 'Kayin State', 'city' => 'Kyaikdon', 'postal_code' => '13072'],
            ['zone' => 'Kayin State', 'city' => 'Phayar Thonesu', 'postal_code' => '13073'],
            ['zone' => 'Kayin State', 'city' => 'ThinkhanNyinaung', 'postal_code' => '13052'],
            ['zone' => 'Kayin State', 'city' => 'Latetho', 'postal_code' => '13023'],
            ['zone' => 'Kayin State', 'city' => 'Bawgali', 'postal_code' => '13024'],

            // TANINTHARYI REGION
            ['zone' => 'Tanintharyi Region', 'city' => 'Dawei', 'postal_code' => '14011'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Myeik', 'postal_code' => '14051'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kawthaung', 'postal_code' => '14091'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Maungmagun', 'postal_code' => '14042'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Thayetchaung', 'postal_code' => '14031'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Yephyu', 'postal_code' => '14021'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kanbauk', 'postal_code' => '14022'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Myeik Cantonment', 'postal_code' => '14053'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Paloug', 'postal_code' => '14064'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Dawei University', 'postal_code' => '14043'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Launglone', 'postal_code' => '14041'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kyunzu', 'postal_code' => '14101'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Palaw', 'postal_code' => '14062'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Tanintharyi', 'postal_code' => '14071'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Bokpyin', 'postal_code' => '14081'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kyaukmetaung', 'postal_code' => '14012'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Heinda', 'postal_code' => '14013'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Dawei Cantonment', 'postal_code' => '14014'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kyauknimaw', 'postal_code' => '14044'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Nyaungzin', 'postal_code' => '14032'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kaleinaung', 'postal_code' => '14023'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Pala', 'postal_code' => '14062'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Shatpon', 'postal_code' => '14063'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Kawthaung Cantonment', 'postal_code' => '14092'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Pyigyimandaing', 'postal_code' => '14083'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Khamoukgyi', 'postal_code' => '14093'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Myittar', 'postal_code' => '14015'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Karathuri', 'postal_code' => '14082'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Myeik University', 'postal_code' => '14052'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Myeik Myotthit', 'postal_code' => '14054'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Maungmalshaung', 'postal_code' => '14016'],
            ['zone' => 'Tanintharyi Region', 'city' => 'Thakyettaw', 'postal_code' => '14045'],
        ];

        foreach ($codes as $code) {
            $zone = ShippingZone::where('name', $code['zone'])
                ->where('country', 'Myanmar')
                ->first();

            if (!$zone) {
                dump("Zone not found: ".$code['zone']);
                continue;
            }

            PostalCode::updateOrCreate(
                [
                    'shipping_zone_id' => $zone->id,
                    'postal_code' => $code['postal_code'],
                ],
                [
                    'country' => 'Myanmar',
                    'city' => $code['city'],
                ]
            );
        }
    }
}
